version: '3.4'

services:
  cardsserver.api:
    image: ${DOCKER_REGISTRY-}cardsserverapi
    build:
      context: .
      dockerfile: CardsServer.API/Dockerfile
    ports:
        - "5070:8080"
        - "5071:8081"
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres
#       - POSTGRES_DB=cardsdb
#       - ConnectionStrings__DefaultConnection=Host=postgres;Port=5433;Database=cardsdb;Username=postgres;Password=postgres
#     depends_on:
#       - postgres

#   postgres:
#     image: postgres:14
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: cardsdb
#     ports:
#       - "5433:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data: