version: '3.6'

networks:
  cards-network:
    name: cards-network
    driver: bridge

services:
  rabbitmq:
    image: rabbitmq:3-management
    networks:
      - cards-network
    container_name: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    # ”величиваем место на диске до 2гб
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq/mnesia
    ports:
      - 15672:15672
       # публиковать порт нужно не всегда. Если консьюмеры и паблишеры находятся внутри docker-compose или подключены к его сети, в этом нет необходимости. 
      - 5672:5672
