version: '3.6'

networks:
  cards-network:
    name: cards-network
    driver: bridge

services:
  cardsserver.api:
    environment:
      CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
    networks:
      - cards-network
    container_name: main
    restart: always
    mem_limit: 500m
    mem_reservation: 30m
    build:
      context: .
      dockerfile: CardsServer.API/Dockerfile
    ports:
        - "1312:8080"
