name: Pleiades-server
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Добавление SSH key
        env:
            SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
            mkdir -p /home/runner/.ssh
            ssh-keyscan ${{ secrets.SSH_HOST }} >> /home/runner/.ssh/known_hosts
            echo "${{ secrets.SSH_KEY }}" > /home/runner/.ssh/github_actions
            chmod 600 /home/runner/.ssh/github_actions
            ssh-agent -a $SSH_AUTH_SOCK > /dev/null
            ssh-add /home/runner/.ssh/github_actions

      - name: Клонирование репозитория на удаленный сервер
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "Проверяем, существует ли директория..."
            if [ -d "/var/www/pleiades-server" ]; then
              echo "Удаляем репозиторий..."
              sudo rm -rf /var/www/pleiades-server/.*
            fi
            echo "Клонируем новый..."
            git clone https://github.com/HinodeMyojo/cards-server.git /var/www/pleiades-server/


      # - name: Копирование Protos в cards-server
      #   uses: appleboy/ssh-action@v0.1.6
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USERNAME }}
      #     key: ${{ secrets.SSH_KEY }}
      #     script: |
      #       if [ -d "/var/www/pleiades-server/AnalyticService/StatisticService.API/Protos" ]; then
      #         echo "Копируем протобуф..."
      #         cp -r /var/www/pleiades-server/AnalyticService/StatisticService.API/Protos /var/www/pleiades-server/cards-server/CardsServer.BLL/
      #       else
      #         echo "Протобуфа нема, ошибка."
      #         exit 1
      #       fi

      - name: Деплой сервера
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/pleiades-server/
            echo "Останавливаем старые контейнера и удаляем старые..."
            docker-compose -f docker-compose-prod.yml down
            docker system prune -f
            echo "Билдим и стартуем новые..."
            docker-compose -f docker-compose-prod.yml up -d --build


